### PR TITLE
Fix Windows-style (CRLF) line endings

### PR DESCRIPTION
**Pull request by rjc**

### CODE REVIEW

**Comment by rjc** [comment]
Hi @paulehoffman,

A bit drastic, I know, but I don't know if there's a better way to fix `CRLF` line endings.

If you work on Windows, please consider configuring your [Git client to handle it automatically](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration).

Regards,

Raf

**Comment by rjc** [comment]
Ping.

**Comment by paulehoffman** [comment]
I'm going to close this without fixing. The vast majority of folks using this tool will be on a Mac or Linux box, and adding CRLF will make it harder for them to use it. The newest version (1.17) explicitly states that using this on Windows requires WSL2, which show the README must fine.

**Comment by rjc** [comment]
You got it completely the wrong way around - what's there now **is** `CRLF` aka _Windows-style line endings_. What I'm proposing with this PR is converting them to `LF` aka _Unix-style line endings_ which **are** the default on Linux, macOS, the *BSDs (most modern Unix-like operating systems, really).

**Comment by paulehoffman** [comment]
Yipes, you are correct. Or, in this case, you were; I just pushed a fix to make them all LF. Sorry for misreading the status in my own editor!

**Comment by rjc** [comment]
> Sorry for misreading the status in my own editor!

Hahaha! No worries! :^D

Better late than never! :^P

Some editors are trying to be _helpful_ by hiding any and all information about whitespace and/or non-printable characters... that's why I like `vi(1)` so much ;^)

That explains why it's taken you a while to reply - you thought I asked for the opposite. The fact that `git diff` isn't showing it properly either, doesn't help :^P

**Pull request closed without merging**
